# Generated by Django 6.0.5 on 2026-05-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appA", "0001_initial"),
        ("appB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appB.modelb"
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appA.modela"
                    ),
                ),
            ],
        ),
    ]
